import { Chapter } from '../types';

export const CORE_CHAPTERS: Chapter[] = [
  // ==========================================
  // CLASS 3 (Grade 3)
  // ==========================================
  {
    id: 'g3-eng',
    title: 'English: Grammar, Stories & Vocabulary',
    subject: 'English',
    grade: 'Grade 3',
    stage: 'Core Concepts',
    topics: [
      {
        id: 'g3-eng-grammar-vocab',
        title: 'Grammar, Vocabulary & Parts of Speech',
        description: 'Pronouns, prepositions, conjunctions, prefixes/suffixes, and building sentence fluency.',
        chapterTitle: 'English: Grammar, Stories & Vocabulary',
        subject: 'English',
        grade: 'Grade 3',
        difficulty: 'Explorer',
        estimatedMinutes: 8,
        keyConcepts: ['Grammar', 'Vocabulary', 'Pronouns & Prepositions', 'Synonyms & Antonyms'],
        subtopics: ['Personal pronouns', 'Prepositions of place (in, on, under, behind)', 'Opposite words & compound words'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'g3-eng-reading-writing',
        title: 'Reading Comprehension, Stories, Poems & Writing',
        description: 'Reading comprehension passages, extracting themes from poems, and writing short paragraphs.',
        chapterTitle: 'English: Grammar, Stories & Vocabulary',
        subject: 'English',
        grade: 'Grade 3',
        difficulty: 'Explorer',
        estimatedMinutes: 9,
        keyConcepts: ['Reading comprehension', 'Paragraph/letter writing', 'Stories and poems'],
        subtopics: ['Unseen short stories', 'Identifying moral and characters', 'Writing a 5-sentence personal paragraph'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g3-math',
    title: 'Mathematics: Operations, Fractions & Geometry',
    subject: 'Mathematics',
    grade: 'Grade 3',
    stage: 'Core Concepts',
    topics: [
      {
        id: 'g3-math-times',
        title: 'Four Basic Operations & Large Numbers (to 10,000)',
        description: 'Mastering multiplication tables, long division basics, 4-digit addition and subtraction.',
        chapterTitle: 'Mathematics: Operations, Fractions & Geometry',
        subject: 'Mathematics',
        grade: 'Grade 3',
        difficulty: 'Explorer',
        estimatedMinutes: 9,
        keyConcepts: ['Large numbers', 'Four basic operations', 'Multiplication tables', 'Division basics'],
        subtopics: ['4-digit place value', 'Multiplication by 1-digit numbers', 'Division as sharing and grouping'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'g3-math-fractions-geo',
        title: 'Fractions, Geometry, Measurement & Data',
        description: 'Halves, thirds, quarters, 2D line segments, standard metric units (kg, litre, metre), and pictographs.',
        chapterTitle: 'Mathematics: Operations, Fractions & Geometry',
        subject: 'Mathematics',
        grade: 'Grade 3',
        difficulty: 'Challenger',
        estimatedMinutes: 9,
        keyConcepts: ['Fractions', 'Geometry', 'Measurement', 'Data handling', 'Perimeter basics'],
        subtopics: ['Unit fractions (1/2, 1/3, 1/4)', 'Rays, lines, and corners', 'Reading pictographs & tally charts'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g3-sci',
    title: 'Science/EVS: Living Things, Body & Materials',
    subject: 'Science',
    grade: 'Grade 3',
    stage: 'Core Concepts',
    topics: [
      {
        id: 'g3-sci-living',
        title: 'Living & Non-Living Things, Plants & Animals',
        description: 'Characteristics of life, plant leaves, roots, herbivore/carnivore diets, and birds of India.',
        chapterTitle: 'Science/EVS: Living Things, Body & Materials',
        subject: 'Science',
        grade: 'Grade 3',
        difficulty: 'Explorer',
        estimatedMinutes: 8,
        keyConcepts: ['Living and non-living things', 'Plants and animals', 'Habitats'],
        subtopics: ['How plants breathe and make food', 'Beaks and claws of birds', 'Classification of animals'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'g3-sci-matter-motion',
        title: 'Human Body, Matter, Materials, Force & Water',
        description: 'Bones and muscles, sensory organs, solid/liquid/gas states, pushing and pulling forces, and clean water.',
        chapterTitle: 'Science/EVS: Living Things, Body & Materials',
        subject: 'Science',
        grade: 'Grade 3',
        difficulty: 'Explorer',
        estimatedMinutes: 9,
        keyConcepts: ['Human body', 'Matter and materials', 'Force and motion', 'Water and air'],
        subtopics: ['Skeletal framework', 'States of matter', 'Push, pull, and friction basics'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g3-sst',
    title: 'Social Studies: Family, Society, Maps & Communities',
    subject: 'Social Science',
    grade: 'Grade 3',
    stage: 'Core Concepts',
    topics: [
      {
        id: 'g3-sst-community-maps',
        title: 'Family & Society, Maps, Directions & Government',
        description: 'Cardinal directions (North, South, East, West), village Panchayat, municipal councils, and festivals of India.',
        chapterTitle: 'Social Studies: Family, Society, Maps & Communities',
        subject: 'Social Science',
        grade: 'Grade 3',
        difficulty: 'Explorer',
        estimatedMinutes: 8,
        keyConcepts: ['Family and society', 'Maps and directions', 'Government and communities', 'History basics'],
        subtopics: ['Compass directions and reading map keys', 'Local village and city administration', 'National symbols and heritage'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },

  // ==========================================
  // CLASS 4 (Grade 4)
  // ==========================================
  {
    id: 'g4-eng',
    title: 'English: Tenses, Writing & Comprehension',
    subject: 'English',
    grade: 'Grade 4',
    stage: 'Core Concepts',
    topics: [
      {
        id: 'g4-eng-grammar-writing',
        title: 'Grammar, Tenses, Paragraphs & Letters',
        description: 'Past, present, and future tenses, informal letters to friends/family, and descriptive composition.',
        chapterTitle: 'English: Tenses, Writing & Comprehension',
        subject: 'English',
        grade: 'Grade 4',
        difficulty: 'Challenger',
        estimatedMinutes: 9,
        keyConcepts: ['Grammar', 'Paragraph/letter writing', 'Vocabulary', 'Verb tenses'],
        subtopics: ['Simple past & continuous tenses', 'Informal letter format', 'Homophones and idioms'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g4-math',
    title: 'Mathematics: Large Numbers, Decimals & Perimeter',
    subject: 'Mathematics',
    grade: 'Grade 4',
    stage: 'Core Concepts',
    topics: [
      {
        id: 'g4-math-ops-fractions',
        title: 'Large Numbers, Four Operations & Fractions',
        description: 'Numbers up to 6 digits, equivalent fractions, mixed numbers, and long division with remainders.',
        chapterTitle: 'Mathematics: Large Numbers, Decimals & Perimeter',
        subject: 'Mathematics',
        grade: 'Grade 4',
        difficulty: 'Challenger',
        estimatedMinutes: 10,
        keyConcepts: ['Large numbers', 'Four basic operations', 'Fractions', 'Decimals'],
        subtopics: ['Indian place value chart (Lakhs)', 'Adding & subtracting like fractions', 'Converting fractions to decimals (0.5, 0.25)'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'g4-math-geo-perimeter',
        title: 'Geometry, Measurement, Perimeter & Data Handling',
        description: 'Angles (acute, right, obtuse), calculating perimeter of polygons, and creating bar graphs.',
        chapterTitle: 'Mathematics: Large Numbers, Decimals & Perimeter',
        subject: 'Mathematics',
        grade: 'Grade 4',
        difficulty: 'Challenger',
        estimatedMinutes: 10,
        keyConcepts: ['Geometry', 'Measurement', 'Data handling', 'Perimeter and area'],
        subtopics: ['Perimeter of squares & rectangles', 'Protractor angle measurements', 'Interpreting vertical bar graphs'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g4-sci',
    title: 'Science/EVS: Ecosystems, Matter & Forces',
    subject: 'Science',
    grade: 'Grade 4',
    stage: 'Core Concepts',
    topics: [
      {
        id: 'g4-sci-foodchain',
        title: 'Living Systems, Plants, Animals & Food Chains',
        description: 'Plant adaptation in deserts/mountains, herbivores, carnivores, omnivores, and producer-consumer chains.',
        chapterTitle: 'Science/EVS: Ecosystems, Matter & Forces',
        subject: 'Science',
        grade: 'Grade 4',
        difficulty: 'Explorer',
        estimatedMinutes: 9,
        keyConcepts: ['Living and non-living things', 'Plants and animals', 'Food chain', 'Adaptations'],
        subtopics: ['Producers, primary & apex consumers', 'Aquatic & desert plant adaptations', 'Decomposers in soil'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'g4-sci-forces-matter',
        title: 'Human Digestion, Matter, Force, Motion & Water',
        description: 'The digestive journey (stomach, intestines), physical states of matter, gravity, friction, and water cycle.',
        chapterTitle: 'Science/EVS: Ecosystems, Matter & Forces',
        subject: 'Science',
        grade: 'Grade 4',
        difficulty: 'Challenger',
        estimatedMinutes: 10,
        keyConcepts: ['Human body', 'Matter and materials', 'Force and motion', 'Water and air', 'Environment'],
        subtopics: ['Digestion and dental care', 'Condensation and evaporation in weather', 'Frictional force and simple levers'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g4-sst',
    title: 'Social Studies: Physical Geography of India & History',
    subject: 'Social Science',
    grade: 'Grade 4',
    stage: 'Core Concepts',
    topics: [
      {
        id: 'g4-sst-geography-history',
        title: 'Geography Basics, History Basics & Government',
        description: 'The Himalayas, Northern Plains, Thar Desert, Coastal Plains, early kingdoms, and democratic rights.',
        chapterTitle: 'Social Studies: Physical Geography of India & History',
        subject: 'Social Science',
        grade: 'Grade 4',
        difficulty: 'Explorer',
        estimatedMinutes: 9,
        keyConcepts: ['Geography basics', 'History basics', 'Government and communities', 'Maps and directions'],
        subtopics: ['Major physical divisions of India', 'Life in coastal vs plateau regions', 'Fundamental duties of citizens'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },

  // ==========================================
  // CLASS 5 (Grade 5)
  // ==========================================
  {
    id: 'g5-eng',
    title: 'English: Advanced Grammar, Essays & Comprehension',
    subject: 'English',
    grade: 'Grade 5',
    stage: 'Core Concepts',
    topics: [
      {
        id: 'g5-eng-grammar-comp',
        title: 'Grammar, Reading Comprehension, Vocabulary & Writing',
        description: 'Active voice, conjunctions, direct speech basics, formal leave applications, and critical reading.',
        chapterTitle: 'English: Advanced Grammar, Essays & Comprehension',
        subject: 'English',
        grade: 'Grade 5',
        difficulty: 'Challenger',
        estimatedMinutes: 10,
        keyConcepts: ['Grammar', 'Reading comprehension', 'Vocabulary', 'Paragraph/letter writing', 'Stories and poems'],
        subtopics: ['Subject-verb agreement', 'Formal letters to school principal', 'Identifying central themes & metaphors'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g5-math',
    title: 'Mathematics: Decimals, Area, Perimeter & Operations',
    subject: 'Mathematics',
    grade: 'Grade 5',
    stage: 'Core Concepts',
    topics: [
      {
        id: 'g5-math-fractions-decimals',
        title: 'Large Numbers, Four Operations, Fractions & Decimals',
        description: 'Numbers up to 8 digits (Crores), BODMAS rules, unlike fractions addition, and decimal arithmetic.',
        chapterTitle: 'Mathematics: Decimals, Area, Perimeter & Operations',
        subject: 'Mathematics',
        grade: 'Grade 5',
        difficulty: 'Challenger',
        estimatedMinutes: 11,
        keyConcepts: ['Large numbers', 'Four basic operations', 'Fractions', 'Decimals'],
        subtopics: ['BODMAS / PEMDAS order of operations', 'LCM and HCF of numbers', 'Decimal multiplication and division'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'g5-math-geometry',
        title: 'Geometry, Measurement, Perimeter, Area & Data',
        description: 'Triangles, circles (radius, diameter, circumference), area of rectangles, volume of cubes, and bar charts.',
        chapterTitle: 'Mathematics: Decimals, Area, Perimeter & Operations',
        subject: 'Mathematics',
        grade: 'Grade 5',
        difficulty: 'Master',
        estimatedMinutes: 11,
        keyConcepts: ['Geometry', 'Measurement', 'Data handling', 'Perimeter and area'],
        subtopics: ['Area = length × breadth', 'Volume of a cuboid', 'Circle parts: radius, chord, and diameter', 'Interpreting pie charts and double bar graphs'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g5-sci',
    title: 'Science/EVS: Respiratory, Circulatory, Matter & Space',
    subject: 'Science',
    grade: 'Grade 5',
    stage: 'Core Concepts',
    topics: [
      {
        id: 'g5-sci-body-systems',
        title: 'Human Body, Respiration, Circulation & Health',
        description: 'The human heart, lungs, blood vessels, deficiency diseases, vitamins, and communicable infections.',
        chapterTitle: 'Science/EVS: Respiratory, Circulatory, Matter & Space',
        subject: 'Science',
        grade: 'Grade 5',
        difficulty: 'Challenger',
        estimatedMinutes: 10,
        keyConcepts: ['Human body', 'Living and non-living things', 'Plants and animals'],
        subtopics: ['Inhalation, exhalation & diaphragm', 'Nutrient balance & deficiency diseases', 'First aid and hygiene'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'g5-sci-forces-space',
        title: 'Matter, Force & Motion, Water, Air & Environment',
        description: 'Solubility, gravity, friction, simple machines (pulley, wheel, lever), atmosphere layers, and renewable energy.',
        chapterTitle: 'Science/EVS: Respiratory, Circulatory, Matter & Space',
        subject: 'Science',
        grade: 'Grade 5',
        difficulty: 'Challenger',
        estimatedMinutes: 10,
        keyConcepts: ['Matter and materials', 'Force and motion', 'Water and air', 'Environment'],
        subtopics: ['Troposphere, stratosphere and ozone', '6 simple machines', 'Water purification and conservation methods'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g5-sst',
    title: 'Social Studies: Freedom Struggle, Globe & Indian Govt',
    subject: 'Social Science',
    grade: 'Grade 5',
    stage: 'Core Concepts',
    topics: [
      {
        id: 'g5-sst-history-geography',
        title: 'History Basics, Geography Basics, Maps & Democracy',
        description: '1857 Revolt to Indian Independence, latitudes and longitudes, continents, and the Indian Parliament structure.',
        chapterTitle: 'Social Studies: Freedom Struggle, Globe & Indian Govt',
        subject: 'Social Science',
        grade: 'Grade 5',
        difficulty: 'Explorer',
        estimatedMinutes: 10,
        keyConcepts: ['History basics', 'Geography basics', 'Government and communities', 'Maps and directions'],
        subtopics: ['Mahatma Gandhi and freedom fighters', 'Equator, tropics, and climate zones', 'Lok Sabha, Rajya Sabha & President of India'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
];
