import { Chapter } from '../types';

export const FOUNDATIONAL_CHAPTERS: Chapter[] = [
  // ==========================================
  // KG – KINDERGARTEN
  // ==========================================
  {
    id: 'kg-eng',
    title: 'English: Alphabets, Phonics & Rhymes',
    subject: 'English',
    grade: 'KG',
    stage: 'Basics & Foundational Skills',
    topics: [
      {
        id: 'kg-eng-alphabet',
        title: 'Alphabets & Phonics (A to Z)',
        description: 'Letter recognition, phonetic sounds, and associating letters with everyday words.',
        chapterTitle: 'English: Alphabets, Phonics & Rhymes',
        subject: 'English',
        grade: 'KG',
        difficulty: 'Explorer',
        estimatedMinutes: 5,
        keyConcepts: ['Alphabets', 'Phonics', 'Letter sounds', 'Beginning sounds'],
        subtopics: ['Uppercase and lowercase letters', 'Phonic sounds A-Z', 'Letter-picture association'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'kg-eng-simplewords',
        title: 'Simple Words, Rhymes & Sentences',
        description: 'Blends, 3-letter CVC sight words, nursery rhymes, and expressing simple sentences.',
        chapterTitle: 'English: Alphabets, Phonics & Rhymes',
        subject: 'English',
        grade: 'KG',
        difficulty: 'Explorer',
        estimatedMinutes: 6,
        keyConcepts: ['Simple words', 'Rhymes', 'Basic sentences', 'Sight words'],
        subtopics: ['3-letter words (cat, dog, sun)', 'Rhyming word pairs', 'Simple greetings & sentences'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'kg-math',
    title: 'Maths: Numbers, Shapes & Counting',
    subject: 'Mathematics',
    grade: 'KG',
    stage: 'Basics & Foundational Skills',
    topics: [
      {
        id: 'kg-math-counting',
        title: 'Numbers & Counting (1 to 20)',
        description: 'Recognizing numbers, counting tangible objects, and number sequencing.',
        chapterTitle: 'Maths: Numbers, Shapes & Counting',
        subject: 'Mathematics',
        grade: 'KG',
        difficulty: 'Explorer',
        estimatedMinutes: 5,
        keyConcepts: ['Numbers', 'Counting', 'Number sequence', 'Quantity'],
        subtopics: ['Counting objects 1 to 20', 'Number identification', 'Before, after, and between'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'kg-math-shapes',
        title: 'Shapes, Patterns & Spatial Sense',
        description: 'Exploring circles, squares, triangles, and recognizing repeating patterns.',
        chapterTitle: 'Maths: Numbers, Shapes & Counting',
        subject: 'Mathematics',
        grade: 'KG',
        difficulty: 'Explorer',
        estimatedMinutes: 5,
        keyConcepts: ['Shapes', 'Patterns', 'Visual discrimination'],
        subtopics: ['Circles, squares, rectangles, triangles', 'Repeating colour/shape patterns', 'Big vs small'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'kg-math-addsub',
        title: 'Addition & Subtraction Basics',
        description: 'Early concept of putting objects together and taking away items with visual cues.',
        chapterTitle: 'Maths: Numbers, Shapes & Counting',
        subject: 'Mathematics',
        grade: 'KG',
        difficulty: 'Explorer',
        estimatedMinutes: 6,
        keyConcepts: ['Addition basics', 'Subtraction basics', 'Counting forward & backward'],
        subtopics: ['Adding with fingers & toys', 'Taking away objects', 'Concepts of more and less'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'kg-evs',
    title: 'EVS: Myself, Family, Animals & Nature',
    subject: 'Environmental Studies',
    grade: 'KG',
    stage: 'Basics & Foundational Skills',
    topics: [
      {
        id: 'kg-evs-senses',
        title: 'Myself, My Family & The Five Senses',
        description: 'Introducing oneself, family bonds, body parts, and the 5 senses of sight, smell, taste, hearing, and touch.',
        chapterTitle: 'EVS: Myself, Family, Animals & Nature',
        subject: 'Environmental Studies',
        grade: 'KG',
        difficulty: 'Explorer',
        estimatedMinutes: 5,
        keyConcepts: ['Myself', 'Family', 'Sense organs', 'Body parts'],
        subtopics: ['Introducing my name & age', 'Nuclear & joint family', 'Eyes, ears, nose, tongue, skin'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'kg-evs-nature',
        title: 'Animals, Plants, Food, Colours & Seasons',
        description: 'Observing friendly animals, green plants, healthy fruits, vivid colours, and weather changes.',
        chapterTitle: 'EVS: Myself, Family, Animals & Nature',
        subject: 'Environmental Studies',
        grade: 'KG',
        difficulty: 'Explorer',
        estimatedMinutes: 6,
        keyConcepts: ['Animals', 'Plants', 'Food', 'Colours', 'Seasons'],
        subtopics: ['Domestic & wild animals', 'Plant leaves & flowers', 'Healthy food habits', 'Sunny, rainy, cold seasons'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'kg-act',
    title: 'Activities: Creative Fun & Puzzles',
    subject: 'Activities',
    grade: 'KG',
    stage: 'Basics & Foundational Skills',
    topics: [
      {
        id: 'kg-act-art-stories',
        title: 'Drawing, Colouring & Storytelling',
        description: 'Expressive drawing, identifying primary colours, and sequencing picture stories.',
        chapterTitle: 'Activities: Creative Fun & Puzzles',
        subject: 'Activities',
        grade: 'KG',
        difficulty: 'Explorer',
        estimatedMinutes: 6,
        keyConcepts: ['Drawing', 'Colouring', 'Storytelling', 'Creativity'],
        subtopics: ['Tracing & drawing basic outlines', 'Colouring inside shapes', 'Listening and narrating short fables'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'kg-act-puzzles',
        title: 'Shape Sorting & Logic Puzzles',
        description: 'Hands-on matching games, odd-one-out discrimination, and jigsaw logic.',
        chapterTitle: 'Activities: Creative Fun & Puzzles',
        subject: 'Activities',
        grade: 'KG',
        difficulty: 'Explorer',
        estimatedMinutes: 5,
        keyConcepts: ['Puzzles', 'Odd one out', 'Sorting', 'Spatial logic'],
        subtopics: ['Matching pairs', 'Finding differences', 'Simple 4-piece jigsaw logic'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },

  // ==========================================
  // CLASS 1 (Grade 1)
  // ==========================================
  {
    id: 'g1-eng',
    title: 'English: Alphabet, Phonics & Parts of Speech',
    subject: 'English',
    grade: 'Grade 1',
    stage: 'Basics & Foundational Skills',
    topics: [
      {
        id: 'g1-eng-phonics',
        title: 'Alphabet & Phonics Blend Mastery',
        description: 'Vowel sounds (A, E, I, O, U), consonant blends (sh, ch, th), and expanding sight vocabulary.',
        chapterTitle: 'English: Alphabet, Phonics & Parts of Speech',
        subject: 'English',
        grade: 'Grade 1',
        difficulty: 'Explorer',
        estimatedMinutes: 7,
        keyConcepts: ['Alphabet & phonics', 'Vowels and consonants', 'Consonant digraphs'],
        subtopics: ['Short and long vowel sounds', 'Word building with blends', 'Phonic rhyming'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'g1-eng-grammar',
        title: 'Nouns, Verbs, Adjectives & Stories',
        description: 'Naming words (nouns), action words (verbs), describing words (adjectives), and short moral poems.',
        chapterTitle: 'English: Alphabet, Phonics & Parts of Speech',
        subject: 'English',
        grade: 'Grade 1',
        difficulty: 'Explorer',
        estimatedMinutes: 7,
        keyConcepts: ['Nouns', 'Verbs', 'Adjectives', 'Reading and simple writing', 'Stories and poems'],
        subtopics: ['Common nouns of people/places', 'Action words in sentences', 'Simple picture reading'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g1-math',
    title: 'Mathematics: Place Value, Operations & Time',
    subject: 'Mathematics',
    grade: 'Grade 1',
    stage: 'Basics & Foundational Skills',
    topics: [
      {
        id: 'g1-math-add',
        title: 'Numbers, Place Value & Addition/Subtraction',
        description: 'Numbers up to 100, tens & ones place value, and 1-digit/2-digit addition and subtraction.',
        chapterTitle: 'Mathematics: Place Value, Operations & Time',
        subject: 'Mathematics',
        grade: 'Grade 1',
        difficulty: 'Explorer',
        estimatedMinutes: 8,
        keyConcepts: ['Numbers and place value', 'Addition & subtraction', 'Tens and ones'],
        subtopics: ['Forward/backward counting to 100', 'Addition with pictures and number lines', 'Subtraction word problems'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'g1-math-measure',
        title: 'Shapes, Measurement, Time & Money',
        description: '2D geometric shapes, comparing lengths, reading the hour hand on clocks, and rupee coins.',
        chapterTitle: 'Mathematics: Place Value, Operations & Time',
        subject: 'Mathematics',
        grade: 'Grade 1',
        difficulty: 'Explorer',
        estimatedMinutes: 8,
        keyConcepts: ['Shapes', 'Measurement', 'Time and money', 'Multiplication basics'],
        subtopics: ['Straight vs curved lines', 'Comparing long/short & heavy/light', 'Days of the week & Indian currency coins'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g1-evs',
    title: 'EVS: Family, Neighbourhood, Plants & Health',
    subject: 'Environmental Studies',
    grade: 'Grade 1',
    stage: 'Basics & Foundational Skills',
    topics: [
      {
        id: 'g1-sci-plants',
        title: 'Family, Neighbourhood, Plants & Animals',
        description: 'Community helpers, parts of green plants, domestic/wild animals, and their natural habitats.',
        chapterTitle: 'EVS: Family, Neighbourhood, Plants & Health',
        subject: 'Environmental Studies',
        grade: 'Grade 1',
        difficulty: 'Explorer',
        estimatedMinutes: 8,
        keyConcepts: ['Family and neighbourhood', 'Plants and animals', 'Community helpers'],
        subtopics: ['Our school & neighbourhood helpers', 'Roots, stems, and leaves', 'Pet, farm, and jungle animals'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'g1-evs-health',
        title: 'Food, Water, Our Body, Transport & Environment',
        description: 'Nutritious meals, drinking clean water, personal hygiene habits, road vehicles, and clean surroundings.',
        chapterTitle: 'EVS: Family, Neighbourhood, Plants & Health',
        subject: 'Environmental Studies',
        grade: 'Grade 1',
        difficulty: 'Explorer',
        estimatedMinutes: 8,
        keyConcepts: ['Food and water', 'Our body', 'Transport and communication', 'Environment'],
        subtopics: ['Meals of the day', 'Water hygiene and saving drops', 'Means of travel: land, water, air'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },

  // ==========================================
  // CLASS 2 (Grade 2)
  // ==========================================
  {
    id: 'g2-eng',
    title: 'English: Grammar, Vocabulary & Reading',
    subject: 'English',
    grade: 'Grade 2',
    stage: 'Basics & Foundational Skills',
    topics: [
      {
        id: 'g2-eng-vocab-nouns',
        title: 'Vocabulary, Nouns, Verbs & Adjectives',
        description: 'Singular/plural nouns, action verbs, colourful describing adjectives, and antonym pairs.',
        chapterTitle: 'English: Grammar, Vocabulary & Reading',
        subject: 'English',
        grade: 'Grade 2',
        difficulty: 'Explorer',
        estimatedMinutes: 8,
        keyConcepts: ['Vocabulary', 'Nouns, verbs, adjectives', 'Singular & plural'],
        subtopics: ['Adding -s and -es to nouns', 'Present tense action verbs', 'Adjectives of color, size, and feelings'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'g2-eng-writing-stories',
        title: 'Reading, Simple Writing, Stories & Poems',
        description: 'Constructing complete sentences with capital letters and full stops; enjoying folklore and poetic meter.',
        chapterTitle: 'English: Grammar, Vocabulary & Reading',
        subject: 'English',
        grade: 'Grade 2',
        difficulty: 'Explorer',
        estimatedMinutes: 8,
        keyConcepts: ['Reading and simple writing', 'Stories and poems', 'Sentence punctuation'],
        subtopics: ['Question marks and full stops', 'Short paragraph construction', 'Moral appreciation of stories'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g2-math',
    title: 'Mathematics: Place Value, Multiplication & Measurements',
    subject: 'Mathematics',
    grade: 'Grade 2',
    stage: 'Basics & Foundational Skills',
    topics: [
      {
        id: 'g2-math-placevalue',
        title: 'Numbers, Place Value & Operations',
        description: '3-digit numbers up to 1000, expanded form, addition with carry-over, and subtraction with borrowing.',
        chapterTitle: 'Mathematics: Place Value, Multiplication & Measurements',
        subject: 'Mathematics',
        grade: 'Grade 2',
        difficulty: 'Explorer',
        estimatedMinutes: 8,
        keyConcepts: ['Numbers and place value', 'Addition & subtraction', 'Regrouping / borrowing'],
        subtopics: ['Hundreds, tens, and ones', 'Addition with regrouping', 'Comparing numbers with >, <, and ='],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'g2-math-mult-time',
        title: 'Multiplication Basics, Shapes, Time & Money',
        description: 'Repeated addition tables (2, 3, 5, 10), solid shapes, reading clocks in half-hours, and rupee transactions.',
        chapterTitle: 'Mathematics: Place Value, Multiplication & Measurements',
        subject: 'Mathematics',
        grade: 'Grade 2',
        difficulty: 'Challenger',
        estimatedMinutes: 9,
        keyConcepts: ['Multiplication basics', 'Shapes', 'Measurement', 'Time and money'],
        subtopics: ['Multiplication as arrays & repeated addition', 'Cylinder, cube, sphere, cone properties', 'Clock reading: o\'clock and half past', 'Notes and coins shopping problems'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g2-evs',
    title: 'EVS: Habitats, Water, Transport & Environment',
    subject: 'Environmental Studies',
    grade: 'Grade 2',
    stage: 'Basics & Foundational Skills',
    topics: [
      {
        id: 'g2-evs-community',
        title: 'Family, Neighbourhood, Plants & Animals',
        description: 'Our diverse neighborhood, domestic vs wild animal shelters, plant types (trees, shrubs, herbs).',
        chapterTitle: 'EVS: Habitats, Water, Transport & Environment',
        subject: 'Environmental Studies',
        grade: 'Grade 2',
        difficulty: 'Explorer',
        estimatedMinutes: 8,
        keyConcepts: ['Family and neighbourhood', 'Plants and animals', 'Animal shelters'],
        subtopics: ['Climbers, creepers, and trees', 'Birds, nests, and insects', 'Good manners in the neighbourhood'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'g2-evs-resources',
        title: 'Food & Water, Body, Transport, Communication & Environment',
        description: 'Clean water storage, healthy posture, land/water/air transport, postal communication, and keeping nature clean.',
        chapterTitle: 'EVS: Habitats, Water, Transport & Environment',
        subject: 'Environmental Studies',
        grade: 'Grade 2',
        difficulty: 'Explorer',
        estimatedMinutes: 8,
        keyConcepts: ['Food and water', 'Our body', 'Transport and communication', 'Environment'],
        subtopics: ['Raw vs cooked food', 'Water cycle in nature', 'Modern communication (telephone, letter, email)', 'Segregating wet and dry waste'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
];
