import { Chapter } from '../types';

export const MIDDLE_CHAPTERS: Chapter[] = [
  // ==========================================
  // CLASS 6 (Grade 6)
  // ==========================================
  {
    id: 'g6-math',
    title: 'Mathematics: Integers, Algebra & Fractions',
    subject: 'Mathematics',
    grade: 'Grade 6',
    stage: 'Deeper Concepts & Problem Solving',
    topics: [
      {
        id: 'g6-math-integers-fractions',
        title: 'Integers, Fractions & Decimals',
        description: 'Positive and negative numbers on the number line, operations with integers, and fractions/decimals mastery.',
        chapterTitle: 'Mathematics: Integers, Algebra & Fractions',
        subject: 'Mathematics',
        grade: 'Grade 6',
        difficulty: 'Challenger',
        estimatedMinutes: 10,
        keyConcepts: ['Integers', 'Fractions and decimals', 'Number line', 'Rational concepts'],
        subtopics: ['Negative numbers and absolute values', 'Rules of integer signs (+ and -)', 'Decimals in measurement'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'g6-math-algebra-ratio',
        title: 'Ratio, Proportion, Algebra & Geometry Basics',
        description: 'Variables and algebraic expressions, unitary method for ratios, basic geometric ideas, and symmetry.',
        chapterTitle: 'Mathematics: Integers, Algebra & Fractions',
        subject: 'Mathematics',
        grade: 'Grade 6',
        difficulty: 'Challenger',
        estimatedMinutes: 11,
        keyConcepts: ['Ratio and proportion', 'Algebra', 'Geometry', 'Mensuration'],
        subtopics: ['Variables and constants in expressions', 'Unitary method in direct ratios', 'Points, intersecting lines, polygons'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g6-sci',
    title: 'Science: Electricity, Light, Living Organisms & Matter',
    subject: 'Science',
    grade: 'Grade 6',
    stage: 'Deeper Concepts & Problem Solving',
    topics: [
      {
        id: 'g6-sci-circuits',
        title: 'Physics & Chemistry: Light, Electricity, Matter & Mixtures',
        description: 'Electric circuits, switches, conductors, shadows, pinhole cameras, and separating mixtures (sedimentation, filtration).',
        chapterTitle: 'Science: Electricity, Light, Living Organisms & Matter',
        subject: 'Science',
        grade: 'Grade 6',
        difficulty: 'Challenger',
        estimatedMinutes: 11,
        keyConcepts: ['Electricity', 'Light', 'Matter', 'Mixtures', 'Force and motion'],
        subtopics: ['Complete and open electric circuits', 'Transparent, translucent, and opaque bodies', 'Filtration, decantation, and evaporation'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'g6-sci-bio-env',
        title: 'Biology & Environment: Cells, Plants, Body & Habitats',
        description: 'Plant roots (taproot vs fibrous), leaf venation, human joint types, animal adaptations, and recycling.',
        chapterTitle: 'Science: Electricity, Light, Living Organisms & Matter',
        subject: 'Science',
        grade: 'Grade 6',
        difficulty: 'Explorer',
        estimatedMinutes: 10,
        keyConcepts: ['Cells', 'Plants', 'Animals', 'Human body', 'Environment and natural resources'],
        subtopics: ['Ball-and-socket vs hinge joints', 'Aquatic vs terrestrial habitats', 'Vermicomposting and plastic waste management'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g6-sst',
    title: 'Social Science: Ancient India, Globe & Local Governance',
    subject: 'Social Science',
    grade: 'Grade 6',
    stage: 'Deeper Concepts & Problem Solving',
    topics: [
      {
        id: 'g6-sst-ancient-civics',
        title: 'Ancient History, Earth & Democracy Basics',
        description: 'Indus Valley Civilisation, Ashoka the Great, motions of the Earth (rotation/revolution), and Panchayati Raj.',
        chapterTitle: 'Social Science: Ancient India, Globe & Local Governance',
        subject: 'Social Science',
        grade: 'Grade 6',
        difficulty: 'Explorer',
        estimatedMinutes: 10,
        keyConcepts: ['Ancient and medieval India/world history', 'Earth, resources, climate', 'Government, democracy, constitution'],
        subtopics: ['Harappan town planning & seals', 'Day/night and seasonal cycles of Earth', 'Gram Sabha and Ward members'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g6-eng',
    title: 'Languages: Grammar, Literature & Composition',
    subject: 'English',
    grade: 'Grade 6',
    stage: 'Deeper Concepts & Problem Solving',
    topics: [
      {
        id: 'g6-eng-language-arts',
        title: 'Grammar, Literature, Comprehension & Creative Writing',
        description: 'Subject-verb agreement, modals, unseen comprehension analysis, short story creation, and formal letters.',
        chapterTitle: 'Languages: Grammar, Literature & Composition',
        subject: 'English',
        grade: 'Grade 6',
        difficulty: 'Challenger',
        estimatedMinutes: 10,
        keyConcepts: ['Grammar', 'Literature', 'Reading comprehension', 'Essay/letter writing', 'Creative writing'],
        subtopics: ['Tenses and modal auxiliaries', 'Character motive in prose', 'Descriptive essay writing format'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },

  // ==========================================
  // CLASS 7 (Grade 7)
  // ==========================================
  {
    id: 'g7-math',
    title: 'Mathematics: Equations, Triangles, Mensuration & Data',
    subject: 'Mathematics',
    grade: 'Grade 7',
    stage: 'Deeper Concepts & Problem Solving',
    topics: [
      {
        id: 'g7-math-algebra-equations',
        title: 'Linear Equations, Ratio & Proportion, Integers',
        description: 'Solving linear equations with balancing method, percentage calculations, profit/loss, and rational numbers.',
        chapterTitle: 'Mathematics: Equations, Triangles, Mensuration & Data',
        subject: 'Mathematics',
        grade: 'Grade 7',
        difficulty: 'Challenger',
        estimatedMinutes: 11,
        keyConcepts: ['Linear equations', 'Ratio and proportion', 'Algebra', 'Integers'],
        subtopics: ['Solving 1-variable equations', 'Percentages and simple interest', 'Rational number operations'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'g7-math-geo-mensuration',
        title: 'Geometry, Mensuration, Data Handling & Probability Basics',
        description: 'Triangle angle sum property, exterior angles, Pythagoras theorem, circle perimeter/area, and mean/median/mode.',
        chapterTitle: 'Mathematics: Equations, Triangles, Mensuration & Data',
        subject: 'Mathematics',
        grade: 'Grade 7',
        difficulty: 'Master',
        estimatedMinutes: 12,
        keyConcepts: ['Geometry', 'Mensuration', 'Data handling', 'Probability basics'],
        subtopics: ['Pythagorean triplets', 'Circumference & area of circles (πr²)', 'Mean, median, and mode', 'Likelihood of coin flips'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g7-sci',
    title: 'Science: Physics, Chemistry & Biology Systems',
    subject: 'Science',
    grade: 'Grade 7',
    stage: 'Deeper Concepts & Problem Solving',
    topics: [
      {
        id: 'g7-sci-heat',
        title: 'Physics & Chemistry: Force, Motion, Light, Heat & Acids/Bases',
        description: 'Conduction/convection/radiation, distance-time graphs, reflection in mirrors, and litmus neutralization.',
        chapterTitle: 'Science: Physics, Chemistry & Biology Systems',
        subject: 'Science',
        grade: 'Grade 7',
        difficulty: 'Challenger',
        estimatedMinutes: 11,
        keyConcepts: ['Force, motion, light, electricity, sound', 'Matter, atoms, mixtures, acids/bases basics'],
        subtopics: ['Speed calculation from distance-time graphs', 'Concave and convex mirrors & image formation', 'Acid + Base → Salt + Water neutralization'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'g7-sci-bio-systems',
        title: 'Biology & Environment: Nutrition, Respiration & Reproduction in Plants',
        description: 'Autotrophic photosynthesis, xylem/phloem transport, human respiration (cellular), and pollination in flowers.',
        chapterTitle: 'Science: Physics, Chemistry & Biology Systems',
        subject: 'Science',
        grade: 'Grade 7',
        difficulty: 'Master',
        estimatedMinutes: 12,
        keyConcepts: ['Cells, plants, animals, human body, reproduction', 'Environment and natural resources'],
        subtopics: ['Stomata and chlorophyll in photosynthesis', 'Aerobic vs anaerobic cellular respiration', 'Stamen, pistil, and seed dispersal mechanisms'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g7-sst',
    title: 'Social Science: Medieval India, Climate & Democracy',
    subject: 'Social Science',
    grade: 'Grade 7',
    stage: 'Deeper Concepts & Problem Solving',
    topics: [
      {
        id: 'g7-sst-medieval-env',
        title: 'Medieval Eras, Earth Layers, Climate & State Government',
        description: 'Delhi Sultanate, Mughal Empire (Akbar, Architecture), crust/mantle/core, water cycle, and Legislative Assemblies (MLA).',
        chapterTitle: 'Social Science: Medieval India, Climate & Democracy',
        subject: 'Social Science',
        grade: 'Grade 7',
        difficulty: 'Explorer',
        estimatedMinutes: 11,
        keyConcepts: ['Ancient and medieval India/world history', 'Earth, resources, climate, agriculture, industries', 'Government, democracy, constitution, rights and duties'],
        subtopics: ['Mughal mansabdari and administration', 'Structure of the atmosphere & ocean currents', 'Role of Chief Minister and Legislative Assembly'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g7-eng',
    title: 'Languages: Grammar, Literature & Formal Writing',
    subject: 'English',
    grade: 'Grade 7',
    stage: 'Deeper Concepts & Problem Solving',
    topics: [
      {
        id: 'g7-eng-writing-analysis',
        title: 'Active/Passive Voice, Direct Speech, Essays & Comprehension',
        description: 'Voice transformation, reported speech, literary prose analysis, persuasive essays, and notice writing.',
        chapterTitle: 'Languages: Grammar, Literature & Formal Writing',
        subject: 'English',
        grade: 'Grade 7',
        difficulty: 'Challenger',
        estimatedMinutes: 11,
        keyConcepts: ['Grammar', 'Literature', 'Reading comprehension', 'Essay/letter writing', 'Creative writing'],
        subtopics: ['Active to passive voice conversion', 'Direct to reported speech rules', 'Writing structured formal letters and notices'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },

  // ==========================================
  // CLASS 8 (Grade 8)
  // ==========================================
  {
    id: 'g8-math',
    title: 'Mathematics: Linear Equations, Mensuration & Factorisation',
    subject: 'Mathematics',
    grade: 'Grade 8',
    stage: 'Deeper Concepts & Problem Solving',
    topics: [
      {
        id: 'g8-math-lineareq',
        title: 'Linear Equations, Factorisation & Algebraic Identities',
        description: 'Solving multi-step linear equations, algebraic identities (a+b)², (a-b)², (a²-b²), and factoring quadratic polynomials.',
        chapterTitle: 'Mathematics: Linear Equations, Mensuration & Factorisation',
        subject: 'Mathematics',
        grade: 'Grade 8',
        difficulty: 'Challenger',
        estimatedMinutes: 12,
        keyConcepts: ['Linear equations', 'Algebra', 'Fractions and decimals', 'Ratio and proportion'],
        subtopics: ['Cross-multiplication in linear equations', 'Standard algebraic identities', 'Factorisation by grouping and splitting'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'g8-math-mensuration-data',
        title: 'Mensuration, Geometry, Data Handling & Probability',
        description: 'Surface areas and volumes of cylinders, cubes, and cuboids; polygons, pie charts, and empirical probability.',
        chapterTitle: 'Mathematics: Linear Equations, Mensuration & Factorisation',
        subject: 'Mathematics',
        grade: 'Grade 8',
        difficulty: 'Master',
        estimatedMinutes: 12,
        keyConcepts: ['Geometry', 'Mensuration', 'Data handling', 'Probability basics'],
        subtopics: ['Total vs lateral surface area', 'Volume of circular cylinders (πr²h)', 'Constructing and reading pie charts', 'Single-event probability ratios'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g8-sci',
    title: 'Science: Forces, Sound, Chemical Effects & Cells',
    subject: 'Science',
    grade: 'Grade 8',
    stage: 'Deeper Concepts & Problem Solving',
    topics: [
      {
        id: 'g8-sci-physics-chem',
        title: 'Physics & Chemistry: Force, Sound, Electricity & Metals/Non-Metals',
        description: 'Pressure (force/area), sound frequency/amplitude, electroplating, chemical properties of metals, and combustion.',
        chapterTitle: 'Science: Forces, Sound, Chemical Effects & Cells',
        subject: 'Science',
        grade: 'Grade 8',
        difficulty: 'Master',
        estimatedMinutes: 12,
        keyConcepts: ['Force, motion, light, electricity, sound', 'Matter, atoms, mixtures, acids/bases basics'],
        subtopics: ['Atmospheric pressure and friction types', 'Loudness (dB) and pitch (Hz)', 'Chemical reactions of metals with oxygen and acids', 'Electroplating and electrolysis'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
      {
        id: 'g8-sci-bio-cells',
        title: 'Biology & Environment: Cell Structure, Microorganisms & Reproduction',
        description: 'Nucleus, cytoplasm, cell membrane, plant cell walls, useful/harmful bacteria, and animal reproduction modes.',
        chapterTitle: 'Science: Forces, Sound, Chemical Effects & Cells',
        subject: 'Science',
        grade: 'Grade 8',
        difficulty: 'Master',
        estimatedMinutes: 12,
        keyConcepts: ['Cells, plants, animals, human body, reproduction', 'Environment and natural resources'],
        subtopics: ['Prokaryotic vs eukaryotic cells', 'Plant vs animal cell organelles', 'Internal vs external fertilization', 'Deforestation and biosphere reserves'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g8-sst',
    title: 'Social Science: Modern India, Resources & Constitution',
    subject: 'Social Science',
    grade: 'Grade 8',
    stage: 'Deeper Concepts & Problem Solving',
    topics: [
      {
        id: 'g8-sst-modern-constitution',
        title: 'Freedom Struggle, Resources, Agriculture & Indian Constitution',
        description: 'British colonial expansion, 1857 Revolt, soil/mineral resources, farming types, and Fundamental Rights in the Indian Constitution.',
        chapterTitle: 'Social Science: Modern India, Resources & Constitution',
        subject: 'Social Science',
        grade: 'Grade 8',
        difficulty: 'Explorer',
        estimatedMinutes: 11,
        keyConcepts: ['Ancient and medieval India/world history', 'Earth, resources, climate, agriculture, industries', 'Government, democracy, constitution, rights and duties'],
        subtopics: ['East India Company to British Crown', 'Substantive farming vs commercial agriculture', 'Six Fundamental Rights and Secularism'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
  {
    id: 'g8-eng',
    title: 'Languages: Advanced Grammar, Literature & Essay Writing',
    subject: 'English',
    grade: 'Grade 8',
    stage: 'Deeper Concepts & Problem Solving',
    topics: [
      {
        id: 'g8-eng-literature-writing',
        title: 'Clauses, Literature Analysis, Argumentative Essays & Reports',
        description: 'Relative and adverbial clauses, critical prose themes, writing formal applications and reasoned editorial essays.',
        chapterTitle: 'Languages: Advanced Grammar, Literature & Essay Writing',
        subject: 'English',
        grade: 'Grade 8',
        difficulty: 'Master',
        estimatedMinutes: 12,
        keyConcepts: ['Grammar', 'Literature', 'Reading comprehension', 'Essay/letter writing', 'Creative writing'],
        subtopics: ['Subordinate and coordinate clauses', 'Critical interpretation of modern literature', 'Editorial letter writing to newspaper editors'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
];
