import { Chapter } from '../types';

export const SECONDARY_CHAPTERS: Chapter[] = [
  // ==========================================
  // CLASS 9 (Grade 9)
  // ==========================================
  {
    id: 'g9-math',
    title: 'Mathematics: Number Systems, Polynomials & Triangles',
    subject: 'Mathematics',
    grade: 'Grade 9',
    stage: 'Advanced Concepts & Board-Exam Prep',
    topics: [
      {
        id: 'g9-math-numbers-poly',
        title: 'Number Systems, Polynomials & Linear Equations',
        description: 'Real numbers, irrationality, remainder theorem, factor theorem, and 2-variable linear equations (ax + by + c = 0).',
        chapterTitle: 'Mathematics: Number Systems, Polynomials & Triangles',
        subject: 'Mathematics',
        grade: 'Grade 9',
        difficulty: 'Challenger',
        estimatedMinutes: 13,
        keyConcepts: ['Number systems', 'Polynomials', 'Linear equations', 'Coordinate geometry'],
        subtopics: ['Irrational numbers and real number line', 'Factorising quadratic polynomials', 'Graphing linear equations in 2 variables'],
        boardSuitability: 'CBSE, ICSE, State Boards (AP / Telangana)',
      },
      {
        id: 'g9-math-geo-mensuration',
        title: 'Triangles, Circles, Areas, Volumes, Statistics & Probability',
        description: 'Congruence criteria (SAS, ASA, SSS, RHS), circle chord theorems, Heron\'s formula, solid volumes, and empirical probability.',
        chapterTitle: 'Mathematics: Number Systems, Polynomials & Triangles',
        subject: 'Mathematics',
        grade: 'Grade 9',
        difficulty: 'Master',
        estimatedMinutes: 14,
        keyConcepts: ['Triangles', 'Circles', 'Areas and volumes', 'Statistics', 'Probability'],
        subtopics: ['Triangle congruence proofs', 'Heron\'s formula for triangle areas', 'Surface areas and volumes of cones and spheres', 'Frequency polygons and probability'],
        boardSuitability: 'CBSE, ICSE, State Boards (AP / Telangana)',
      },
    ],
  },
  {
    id: 'g9-sci-physics',
    title: 'Science (Physics): Motion, Force, Gravitation & Work',
    subject: 'Science',
    grade: 'Grade 9',
    category: 'Physics',
    stage: 'Advanced Concepts & Board-Exam Prep',
    topics: [
      {
        id: 'g9-sci-newton',
        title: 'Motion, Force, Newton\'s Laws & Gravitation',
        description: 'Equations of motion (v = u + at, s = ut + ½at²), Newton\'s 3 laws, universal gravitation, and Archimedes\' principle.',
        chapterTitle: 'Science (Physics): Motion, Force, Gravitation & Work',
        subject: 'Science',
        grade: 'Grade 9',
        difficulty: 'Master',
        estimatedMinutes: 13,
        keyConcepts: ['Motion', 'Force', 'Gravitation', 'Work & energy', 'Sound'],
        subtopics: ['Equations of uniformly accelerated motion', 'Momentum conservation (p = mv)', 'Universal law of gravitation (F = G M m / r²)', 'Work done, kinetic energy (½mv²), and sound waves'],
        boardSuitability: 'CBSE, ICSE, State Boards (AP / Telangana)',
      },
    ],
  },
  {
    id: 'g9-sci-chem-bio',
    title: 'Science (Chemistry & Biology): Matter, Atoms, Cells & Tissues',
    subject: 'Science',
    grade: 'Grade 9',
    category: 'Chemistry & Biology',
    stage: 'Advanced Concepts & Board-Exam Prep',
    topics: [
      {
        id: 'g9-sci-matter-atoms',
        title: 'Matter in Surroundings, Atoms & Molecules',
        description: 'Kinetic theory of matter, Dalton\'s atomic postulates, chemical formula writing, mole concept, and Bohr\'s model.',
        chapterTitle: 'Science (Chemistry & Biology): Matter, Atoms, Cells & Tissues',
        subject: 'Science',
        grade: 'Grade 9',
        difficulty: 'Master',
        estimatedMinutes: 13,
        keyConcepts: ['Matter', 'Atoms', 'Chemical reactions', 'Structure of the atom'],
        subtopics: ['Latent heat of fusion and vaporization', 'Writing formulas with valency & polyatomic ions', 'Rutherford scattering & Bohr model of electron shells'],
        boardSuitability: 'CBSE, ICSE, State Boards (AP / Telangana)',
      },
      {
        id: 'g9-sci-cells-tissues',
        title: 'Cell Biology, Plant & Animal Tissues, and Health',
        description: 'Plasma membrane, mitochondria, plastids, meristematic vs permanent plant tissues, and epithelial/connective tissues.',
        chapterTitle: 'Science (Chemistry & Biology): Matter, Atoms, Cells & Tissues',
        subject: 'Science',
        grade: 'Grade 9',
        difficulty: 'Challenger',
        estimatedMinutes: 12,
        keyConcepts: ['Cell', 'Tissues', 'Life processes', 'Environment'],
        subtopics: ['Prokaryotic vs eukaryotic organelles', 'Xylem, phloem, parenchyma, and sclerenchyma', 'Blood, bone, and muscular tissues'],
        boardSuitability: 'CBSE, ICSE, State Boards (AP / Telangana)',
      },
    ],
  },
  {
    id: 'g9-sst',
    title: 'Social Science: French Revolution, Climate & Democratic Rights',
    subject: 'Social Science',
    grade: 'Grade 9',
    stage: 'Advanced Concepts & Board-Exam Prep',
    topics: [
      {
        id: 'g9-sst-revolution-climate-rights',
        title: 'Major Historical Events, Geography, Democracy & Economics',
        description: 'The French Revolution, Indian drainage basins, monsoon climate, constitutional design, and poverty as a challenge.',
        chapterTitle: 'Social Science: French Revolution, Climate & Democratic Rights',
        subject: 'Social Science',
        grade: 'Grade 9',
        difficulty: 'Challenger',
        estimatedMinutes: 13,
        keyConcepts: ['Major historical events, nationalism, industrialization', 'Resources, climate, water', 'Democracy, constitution, rights', 'Development, sectors of economy'],
        subtopics: ['Storming of the Bastille and legacy of liberty', 'Mechanism of the Indian monsoon winds', 'Preamble and guiding values of Indian Constitution', 'The story of Village Palampur and human capital'],
        boardSuitability: 'CBSE, ICSE, State Boards (AP / Telangana)',
      },
    ],
  },
  {
    id: 'g9-eng',
    title: 'English: Grammar, Literature, Writing Skills & Vocabulary',
    subject: 'English',
    grade: 'Grade 9',
    stage: 'Advanced Concepts & Board-Exam Prep',
    topics: [
      {
        id: 'g9-eng-skills',
        title: 'Integrated Grammar, Descriptive Paragraphs & Literary Prose',
        description: 'Tense consistency, reported speech dialogues, diary entry, formal applications, and classic poetry motifs.',
        chapterTitle: 'English: Grammar, Literature, Writing Skills & Vocabulary',
        subject: 'English',
        grade: 'Grade 9',
        difficulty: 'Master',
        estimatedMinutes: 12,
        keyConcepts: ['Grammar', 'Literature', 'Reading comprehension', 'Writing skills', 'Letter/application', 'Vocabulary'],
        subtopics: ['Reported speech and gap-filling editing', 'Diary entries and descriptive character sketches', 'Poetic devices: imagery, rhyme schemes, and metaphor'],
        boardSuitability: 'CBSE, ICSE, State Boards (AP / Telangana)',
      },
    ],
  },

  // ==========================================
  // CLASS 10 (Grade 10 - Board Examination)
  // ==========================================
  {
    id: 'g10-math',
    title: 'Mathematics: Board Exam Curriculum (Trig, Quadratics, AP)',
    subject: 'Mathematics',
    grade: 'Grade 10',
    stage: 'Advanced Concepts & Board-Exam Prep',
    topics: [
      {
        id: 'g10-math-algebra-quadratics',
        title: 'Real Numbers, Polynomials, Linear & Quadratic Equations, AP',
        description: 'Fundamental Theorem of Arithmetic, quadratic formula (D = b² - 4ac), and Arithmetic Progressions nth term/sum formulas.',
        chapterTitle: 'Mathematics: Board Exam Curriculum (Trig, Quadratics, AP)',
        subject: 'Mathematics',
        grade: 'Grade 10',
        difficulty: 'Master',
        estimatedMinutes: 15,
        keyConcepts: ['Number systems', 'Polynomials', 'Linear equations', 'Quadratic equations', 'Arithmetic progressions'],
        subtopics: ['Proving irrationality of √3 and √5', 'Discriminant and nature of roots', 'AP nth term (a + (n-1)d) and sum Sn = n/2(2a + (n-1)d)'],
        boardSuitability: 'CBSE, ICSE, State Boards (AP / Telangana SSC)',
      },
      {
        id: 'g10-math-trig-geo',
        title: 'Triangles, Coordinate Geometry, Circles & Trigonometry',
        description: 'Basic Proportionality Theorem (Thales), distance & section formula, tangents from external points, sin/cos/tan identities, and Heights & Distances.',
        chapterTitle: 'Mathematics: Board Exam Curriculum (Trig, Quadratics, AP)',
        subject: 'Mathematics',
        grade: 'Grade 10',
        difficulty: 'Master',
        estimatedMinutes: 16,
        keyConcepts: ['Triangles', 'Coordinate geometry', 'Circles', 'Trigonometry', 'Areas and volumes', 'Statistics', 'Probability'],
        subtopics: ['Similarity criteria (AAA, SAS, SSS)', 'Section formula m1x2 + m2x1 / (m1+m2)', 'Trigonometric identities (sin²θ + cos²θ = 1)', 'Angles of elevation & depression word problems', 'Surface areas of combined solids and grouped mean/median/mode'],
        boardSuitability: 'CBSE, ICSE, State Boards (AP / Telangana SSC)',
      },
    ],
  },
  {
    id: 'g10-sci-physics',
    title: 'Science (Physics): Light, Electricity & Magnetism',
    subject: 'Science',
    grade: 'Grade 10',
    category: 'Physics',
    stage: 'Advanced Concepts & Board-Exam Prep',
    topics: [
      {
        id: 'g10-sci-ohmslaw',
        title: 'Electricity, Magnetism & Heating Effects',
        description: 'Ohm\'s law (V = IR), series/parallel resistance combinations, Joule\'s law of heating, magnetic fields, and Fleming\'s left-hand rule.',
        chapterTitle: 'Science (Physics): Light, Electricity & Magnetism',
        subject: 'Science',
        grade: 'Grade 10',
        difficulty: 'Master',
        estimatedMinutes: 15,
        keyConcepts: ['Electricity', 'Magnetism', 'Work & energy', 'Force', 'Sound'],
        subtopics: ['Equivalent resistance calculation', 'Electric power (P = VI = I²R)', 'Magnetic field around straight conductors and solenoids', 'Electromagnetic induction and motors'],
        boardSuitability: 'CBSE, ICSE, State Boards (AP / Telangana SSC)',
      },
      {
        id: 'g10-sci-light-optics',
        title: 'Light (Reflection & Refraction) & The Human Eye',
        description: 'Spherical mirror formula (1/f = 1/v + 1/u), lens formula, Snell\'s law of refraction, prism dispersion, myopia, and hypermetropia.',
        chapterTitle: 'Science (Physics): Light, Electricity & Magnetism',
        subject: 'Science',
        grade: 'Grade 10',
        difficulty: 'Master',
        estimatedMinutes: 15,
        keyConcepts: ['Light', 'Motion', 'Physics board-exam essentials'],
        subtopics: ['Concave mirror ray diagrams & magnification', 'Snell\'s law and refractive index', 'Atmospheric refraction (twinkling of stars)', 'Correction of vision defects using lenses'],
        boardSuitability: 'CBSE, ICSE, State Boards (AP / Telangana SSC)',
      },
    ],
  },
  {
    id: 'g10-sci-chem',
    title: 'Science (Chemistry): Reactions, Acids, Metals & Carbon',
    subject: 'Science',
    grade: 'Grade 10',
    category: 'Chemistry',
    stage: 'Advanced Concepts & Board-Exam Prep',
    topics: [
      {
        id: 'g10-sci-chem-reactions',
        title: 'Chemical Reactions, Acids, Bases & Salts',
        description: 'Balancing chemical equations, redox reactions, pH scale applications, and manufacturing of Bleaching powder, Baking soda, and POP.',
        chapterTitle: 'Science (Chemistry): Reactions, Acids, Metals & Carbon',
        subject: 'Science',
        grade: 'Grade 10',
        difficulty: 'Master',
        estimatedMinutes: 15,
        keyConcepts: ['Chemical reactions', 'Acids/bases/salts', 'Matter', 'Atoms'],
        subtopics: ['Displacement and double displacement equations', 'pH in tooth decay and soil', 'Chlor-alkali process & Plaster of Paris chemistry'],
        boardSuitability: 'CBSE, ICSE, State Boards (AP / Telangana SSC)',
      },
      {
        id: 'g10-sci-metals-carbon',
        title: 'Metals & Non-Metals, Carbon & Its Compounds',
        description: 'Reactivity series, ionic vs covalent bonding, versatile tetravalency of carbon, homologous series, and soap action.',
        chapterTitle: 'Science (Chemistry): Reactions, Acids, Metals & Carbon',
        subject: 'Science',
        grade: 'Grade 10',
        difficulty: 'Master',
        estimatedMinutes: 15,
        keyConcepts: ['Metals/non-metals', 'Carbon compounds', 'Chemical reactions'],
        subtopics: ['Extraction of metals (calcination & roasting)', 'Functional groups (alcohols, aldehydes, carboxylic acids)', 'Micelle formation and cleansing action of soaps'],
        boardSuitability: 'CBSE, ICSE, State Boards (AP / Telangana SSC)',
      },
    ],
  },
  {
    id: 'g10-sci-bio',
    title: 'Science (Biology): Life Processes, Control, Reproduction & Heredity',
    subject: 'Science',
    grade: 'Grade 10',
    category: 'Biology',
    stage: 'Advanced Concepts & Board-Exam Prep',
    topics: [
      {
        id: 'g10-sci-genetics',
        title: 'Life Processes, Control & Coordination, Reproduction, Heredity & Environment',
        description: 'Human nutrition, double circulation, reflex arc, plant tropisms, sexual reproduction in plants/humans, Mendel\'s monohybrid cross, and 10% trophic rule.',
        chapterTitle: 'Science (Biology): Life Processes, Control, Reproduction & Heredity',
        subject: 'Science',
        grade: 'Grade 10',
        difficulty: 'Master',
        estimatedMinutes: 16,
        keyConcepts: ['Life processes', 'Reproduction', 'Heredity', 'Evolution', 'Control & coordination', 'Environment'],
        subtopics: ['Nephron structure and urine formation', 'Neurons, synapses, and human brain parts', 'Mendel\'s laws of inheritance and sex determination in humans', 'Biological magnification and ozone depletion in ecosystems'],
        boardSuitability: 'CBSE, ICSE, State Boards (AP / Telangana SSC)',
      },
    ],
  },
  {
    id: 'g10-sst',
    title: 'Social Science: Nationalism, Resources, Power Sharing & Economics',
    subject: 'Social Science',
    grade: 'Grade 10',
    stage: 'Advanced Concepts & Board-Exam Prep',
    topics: [
      {
        id: 'g10-sst-history-geography',
        title: 'Nationalism in Europe & India, Resources, Agriculture & Minerals',
        description: 'Rise of Nationalism in Europe, Indian Non-Cooperation Movement, Dandi March, soil resources, major crops, and industrial geography.',
        chapterTitle: 'Social Science: Nationalism, Resources, Power Sharing & Economics',
        subject: 'Social Science',
        grade: 'Grade 10',
        difficulty: 'Master',
        estimatedMinutes: 15,
        keyConcepts: ['Major historical events, nationalism, industrialization, India and the modern world', 'Resources, agriculture, industries, climate, water, minerals and energy'],
        subtopics: ['Jallianwala Bagh, Khilafat and Civil Disobedience', 'Rabi, Kharif, and Zaid cropping seasons', 'Conventional and non-conventional energy resources'],
        boardSuitability: 'CBSE, ICSE, State Boards (AP / Telangana SSC)',
      },
      {
        id: 'g10-sst-civics-economics',
        title: 'Power Sharing, Federalism, Sectors of Economy, Money & Credit',
        description: 'Majoritarianism in Sri Lanka vs power sharing in Belgium, Indian federal structure, Primary/Secondary/Tertiary GDP, RBI regulations, and consumer rights.',
        chapterTitle: 'Social Science: Nationalism, Resources, Power Sharing & Economics',
        subject: 'Social Science',
        grade: 'Grade 10',
        difficulty: 'Master',
        estimatedMinutes: 15,
        keyConcepts: ['Democracy, constitution, political institutions, rights, power sharing', 'Development, sectors of economy, money and credit, globalization, consumer rights'],
        subtopics: ['Union, State, and Concurrent legislative lists', 'Formal vs informal sources of credit in rural India', 'MNCs and globalization impacts on producers', 'Consumer Protection Act (COPRA) and consumer forums'],
        boardSuitability: 'CBSE, ICSE, State Boards (AP / Telangana SSC)',
      },
    ],
  },
  {
    id: 'g10-eng',
    title: 'English: Board Exam Grammar, Writing Skills & Literature',
    subject: 'English',
    grade: 'Grade 10',
    stage: 'Advanced Concepts & Board-Exam Prep',
    topics: [
      {
        id: 'g10-eng-board-exam',
        title: 'Grammar, Literature, Reading Comprehension & Writing Skills',
        description: 'Editing/omission, reported speech conversions, letters to editors, analytical paragraphs based on data graphs, and poetry analysis.',
        chapterTitle: 'English: Board Exam Grammar, Writing Skills & Literature',
        subject: 'English',
        grade: 'Grade 10',
        difficulty: 'Master',
        estimatedMinutes: 15,
        keyConcepts: ['Grammar', 'Literature', 'Reading comprehension', 'Writing skills', 'Letter/application', 'Essay/article/report writing', 'Vocabulary'],
        subtopics: ['Formal letters to public authorities & business enquiries', 'Analytical paragraph writing from charts and tables', 'Theme extraction, irony, and symbolism in classic texts'],
        boardSuitability: 'CBSE, ICSE, State Boards (AP / Telangana SSC)',
      },
    ],
  },
  {
    id: 'g10-cs-1',
    title: 'Computer Science: Web Technologies & Cybersecurity',
    subject: 'Computer Science',
    grade: 'Grade 10',
    stage: 'Advanced Concepts & Board-Exam Prep',
    topics: [
      {
        id: 'g10-cs-cybersecurity',
        title: 'Data Privacy, Encryption & Cyber Safety',
        description: 'Symmetric vs asymmetric encryption, phishing defense, digital footprints, and online ethics.',
        chapterTitle: 'Computer Science: Web Technologies & Cybersecurity',
        subject: 'Computer Science',
        grade: 'Grade 10',
        difficulty: 'Master',
        estimatedMinutes: 12,
        keyConcepts: ['Encryption fundamentals', 'Phishing & malware prevention', 'Digital ethics'],
        subtopics: ['Public and private key encryption', 'Safe online banking and 2-factor authentication', 'Intellectual property and digital copyright'],
        boardSuitability: 'CBSE, ICSE, State Boards',
      },
    ],
  },
];
